apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
   color: blue
spec:
  containers:
  - name: myapp
    image: nginx
    volumeMounts:
    - mountPath: /var/www/html/
      name: xyz-vol
    ports:
      - containerPort: 80
    resources:
      requests:
        storage: 100Mi
  volumes:
  - name: xyz-vol
    emptyDir:
      medium: Memory
  