apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /data/mypv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 1Gi  # Match the storage capacity with the PersistentVolume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvpod
  template:
    metadata:
      labels:
        app: pvpod
    spec:
      containers:
        - name: test
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html  # Remove trailing slash
              name: myvol
      volumes:
        - name: myvol
          persistentVolumeClaim:
            claimName: mypvc
