apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloc
  name: helloc
spec:
  containers:
  - image: nginx
    name: helloc
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
