apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: configmap-pod
    image: httpd
    volumeMounts:
    - name: config-vol
      mountPath: /etc/xyz.conf
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: config-vol
      configMap:
       name: logs
       items:
        - key: xyz-vol123
          path: /config.conf