apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
spec:
  replicas: 5
  selector:
    word: green
  template:
    metadata:
      name: mypod
      labels:
        word: green
    spec:
      containers:
        - name: mypod
          image: nginx
          ports:
            - containerPort: 80
